[package]
name = "raccoonv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rv"
path = "src/main.rs"

[dependencies]
capstone = "0.11.0"
elf = "0.7.2"
colored = "2.0.0"
clap = { version = "4.1.6", features = ["derive"] }
